### ISSUE TITLE
No embeddedresource found for WhatsAppUI.App

### ISSUE THREAD

**Issue by leaguefun** [egbakou/BarCodeReader#1]
Buddy, thanks for your awesome sample !!
By the way, I am going to build and run the sample, it's built fine, but it threw an error by "No embeddedresource found for WhatsAppUI.App", do you have any idea ? or what I'd missed ? thanks.
![Screenshot 2019-05-23 at 00 06 51](https://user-images.githubusercontent.com/6715863/58190375-f8382300-7cee-11e9-93de-f50d77e27040.png)

**Comment by egbakou** [comment]
Hello !  You have submitted your issue in the wrong place.
Go to [https://github.com/egbakou/WhatsAppUI](https://github.com/egbakou/WhatsAppUI)
Thanks !
